### PR TITLE
Uses python3 to install awscli-v1 for real this time, not v2

### LINKED ISSUE #29: [BUG] Regression Introduced by PR #28
**Describe the bug**

PR #28's removal of the default/user-space `/bin/python` setup breaks the EL8 builders when the default-value for `spel_aws_cliv1_source` defined in the `spel/minimal-linux.json` file is used.

**Severity**

- [ ] Completely Broken (No work-around evident)
- [ ] Severely Broken (Work-around possible but difficult)
- [ ] Moderately Broken (Trivial work-around)
- [ ] Nuisance (Functions but untrapped errors can slip through)

**To Reproduce**
1. Invoke packer with the default-builders left activated
2. Wait for the `minimal-rhel-8-hvm` and/or `minimal-centos-8-hvm` builders to invoke the `AWSutils.sh`
3. Build faults and exits

**Expected behavior**

Build succeeds as before the build-breaking PR was merged

**Deviance Description**

Build breaks when attempting to install the AWS CLIv2 from the bundled-installer ZIP-file.

~~~
2021/07/23 14:15:13 ui:     minimal-rhel-8-hvm: + chroot /mnt/ec2-root /bin/bash -c '/tmp/awscli-bundle/install -i '\''/usr/local/aws-cli/v1'\'' -b '\''/usr/local/bin/aws'\'''m: /usr/bin/env: ‘python’: No such file or directory
2021/07/23 14:15:13 ui:     minimal-rhel-8-hvm: + err_exit 'Failed installing AWS CLIv1'
~~~

**Screenshots**

**Additional context**

In order to capture the underlying error, it may be necessary to invoke Packer with the `PACKER_LOG=1` and `PACKER_LOG_PATH=/path/to/log-file` environmentals set. 

**Fix Suggestions**

Any of:
* Revert the changes introduced with 6f7e03d 
* Set the default-value for `spel_aws_cliv1_source` in `spel/minimal-linux.json` to null
* Wholly remove the logic for (and variables that support) installation of the AWS CLIv1 from the bundled-installer

### PR DESCRIPTION
**Pull request by lorengordon**
Fixes #29 

Attn: @ferricoxide

### CODE REVIEW

**Comment by ferricoxide** [comment]
As offered, this "fix" breaks the intended logic of the "use the bundled installer". The "install AWS CLIv1 using pip" functionality was [already present](https://github.com/plus3it/amigen8/blob/65690b4200531d3dc7729e5a90ccf4e078606ebd/AWSutils.sh#L127-L133) – the installation-method is run-time selectable and comes from the name of the selected client-source — before the builder-breaking changes introduced in #28. Similarly, the "install using (user-land) Python3" functionality was already present. Ultimately, rolling back PR #28 is the simplest "fix".

**Comment by lorengordon** [comment]
>The "install AWS CLIv1 using pip" functionality was already present

This change is wholly independent of installing using pip.

What changed was awscli-v1.20 deprecated support for python2.7 entirely. Using a specific python runtime when executing the bundled-installer is the supported mechanism.

>Similarly, the "install using (user-land) Python3" functionality was already present.

Through spel, where python3 gets pre-installed before invoking this script, this functionality was also not working.

Not trying to say this patch is "right", exactly. Only goal here is to fix the original intent, re-aligning with amigen7.

**Comment by ferricoxide** [comment]
> > The "install AWS CLIv1 using pip" functionality was already present
> 
> This change is wholly independent of installing using pip.
> 
> What changed was awscli-v1.20 deprecated support for python2.7 entirely. Using a specific python runtime when executing the bundled-installer is the supported mechanism.

But what I'm saying is that, for EL8, py27 ought to be a non-issue. The bundled-installer is still doing "let's see if we've got a Python in our path"; it's just also doing a "bomb-out if it's py27 or older" trap. The `EnsurePy3` function ensures that Python3 is installed (if Python3 is absent the function installs it; if present does nothing). Before the build-breaking PR, the function used `alternatives` to obviate the need for invoking a hard-coded version user-land Python elsewhere.

> 
> > Similarly, the "install using (user-land) Python3" functionality was already present.
> 
> Through spel, where python3 gets pre-installed before invoking this script, this functionality was also not working.

Not sure what this means?

If you're saying that spel is injecting a user-land Python3 before AMIgen is run, my suggestion would be that either the _spel_ logic be updated to call `alternatives`  or we can update the `EnsurePy3` function. Basically, ensure that, regardless of whether the Python3 RPMs are already installed prior its invocation, it will check to see if the `alternatives`-created path exists and, if not, fixes that gap.

> Not trying to say this patch is "right", exactly. Only goal here is to fix the original intent, re-aligning with amigen7.

Unfortunately, EL7 and EL8 don't 100% align, particularly with respect to the separation of system Python and user-land Python. In EL7, there was only system-python; in EL8, there's system Python and user-land Python. Properly setting up user-land Python would tend to be the distro-appropriate path to try to adhere to (with things like the bundled-installer subsequently "doing the Right Thing" based on that setup having been done).

**Comment by lorengordon** [comment]
I am working on testing for spel8 builds, and I am now fairly certain this patch is both correct and necessary.

**Pull request closed without merging**
